---



- hosts: routers

  gather_facts: false

  connection: network_cli



  tasks:

#    - name: change Hostname omoyele

 #     ios_config: 

 #       lines: 

  #        - hostname R1



    - name: Run ospf

      ios_config:

        lines:

         - network 0.0.0.0 255.255.255.255 area 0

        parents: router ospf 2

- hosts: R1

  gather_facts: false

  connection: network_cli



  tasks:

    - name: configure int e1/0 interface

      ios_config:

        lines:

           - ip add 192.168.3.1 255.255.255.0

           - no shutdown

        parents: int e1/0

- hosts: R2

  gather_facts: false

  connection: network_cli



  tasks:

    - name: configure int e1/0 interface

      ios_config:

        lines:

           - ip add 192.168.10.1 255.255.255.0

           - no shutdown

        parents: int e1/0


    - name: configure int s2/0 interface

      ios_config:

        lines:
